### PR TITLE
Tc004

### PR DESCRIPTION
**Pull request by erdemOre**
Would it be better if we add work 2 in @CinarIbrahim  code?
What's your opinion on this Mr @oturkmen160 ?

### CODE REVIEW

**Comment by oturkmen160** [comment]
> 

I totally agree with you :)

**Comment by erdemOre** [comment]
then Mr @CinarIbrahim can u please add work 2 on your code. Thanks

**Comment by CinarIbrahim** [comment]
> > 
> 
> I totally agree with you :)

Omer how can I add work 2 on my code. Can you help me?

**Comment by erdemOre** [comment]
you should first fetch it 
then pull to your local
then make updates
then push
but u have already closed your branch
I don't know what happens now
@oturkmen160  can we reopen it
we'll check it tomarrow

**Pull request merged**
